#!/usr/bin/env python

import sys
from electrumfair import Network
from electrumfair.util import json_encode, print_msg

try:
    addr = sys.argv[1]
except Exception:
    print "usage: get_history <FairCoin_address>"
    sys.exit(1)

n = Network()
n.start()
h = n.synchronous_get(('blockchain.address.get_history',[addr]))
print_msg(json_encode(h))
